
- name: Update apt and install foreman related packages
  become: yes
  apt: 
    update_cache: yes 
    name: "{{ foreman_packages }}"
    state: latest
    
- name: Ansible install Puppet deb file from url
  become: yes
  apt:
    deb: "{{ puppet_source }}/{{ puppet_version }}"

- name: Gather the package facts
  ansible.builtin.package_facts:
    manager: auto

- name: Add Foreman repository
  
  ansible.builtin.apt_repository:
    update_cache: no
    repo: deb http://deb.theforeman.org/ focal 3.0
    state: present

- name: Add Foreman plugins repository
  ansible.builtin.apt_repository:
    update_cache: no
    repo: deb http://deb.theforeman.org/ plugins 3.0
    state: present

- name: Add Foreman apt key from url
  ansible.builtin.apt_key:
    url: https://deb.theforeman.org/pubkey.gpg
    state: present

- name: Chech that {{ hostname }} resolves to host IP
  lineinfile:
    path: /etc/hosts
    regexp: "^{{ default_ipv4_address | regex_escape() }}\\s+{{ hostname | regex_escape() }}\\s+{{ foreman_fqdn | regex_escape() }}\\s*$" 
    line: "{{ default_ipv4_address }}\t{{ hostname }} {{ foreman_fqdn }}"
    state: present
    
- name: Installing "{{ foreman_installer_package }}"
  become: yes
  apt: 
    update_cache: yes 
    name: "{{ foreman_installer_package }}"
    state: latest

- name: Create answers file directory
  file:
    path: /etc/foreman-installer/scenarios.d
    mode: 0755
    state: directory

- name: Generate answers file
  template:
    src: foreman-answers.yaml
    dest: /etc/foreman-installer/scenarios.d/foreman-answers.yaml
    mode: 0600

- name: Configure hostname of Foreman isntaller
  ansible.builtin.replace:
    path: /etc/foreman-installer/scenarios.d/foreman-answers.yaml
    regexp: '<foreman_hostname>'
    replace: "{{ hostname }}"

- name: Configure DB Username of Foreman isntaller
  ansible.builtin.replace:
    path: /etc/foreman-installer/scenarios.d/foreman-answers.yaml
    regexp: '<foreman_db_username>'
    replace: "{{ foreman_db_username }}"

- name: Configure DB Password of Foreman isntaller
  ansible.builtin.replace:
    path: /etc/foreman-installer/scenarios.d/foreman-answers.yaml
    regexp: '<foreman_db_password>'
    replace: "{{ foreman_db_password }}"

- name: Configure TFTP Server IP of Foreman isntaller
  ansible.builtin.replace:
    path: /etc/foreman-installer/scenarios.d/foreman-answers.yaml
    regexp: '<foreman_tftp_server_ip>'
    replace: "{{ foreman_tftp_server_ip }}"


- name: Configure Network Interface of Foreman isntaller
  ansible.builtin.replace:
    path: /etc/foreman-installer/scenarios.d/foreman-answers.yaml
    regexp: '<foreman_interface>'
    replace: "{{ foreman_interface }}"

- name: Configure DHCP Gateway of Foreman isntaller
  ansible.builtin.replace:
    path: /etc/foreman-installer/scenarios.d/foreman-answers.yaml
    regexp: '<foreman_dhcp_gateway>'
    replace: "{{ foreman_dhcp_gateway }}"

- name: Configure DHCP range of Foreman isntaller
  ansible.builtin.replace:
    path: /etc/foreman-installer/scenarios.d/foreman-answers.yaml
    regexp: '<foreman_dhcp_range>'
    replace: "{{ foreman_dhcp_range }}"

- name: Configure DHCP failover address of Foreman isntaller
  ansible.builtin.replace:
    path: /etc/foreman-installer/scenarios.d/foreman-answers.yaml
    regexp: '<foreman_dhcp_failover_address>'
    replace: "{{ foreman_dhcp_failover_address }}"

- name: Configure DB Password of Foreman installer
  ansible.builtin.replace:
    path: /etc/foreman-installer/scenarios.d/foreman-answers.yaml
    regexp: '<foreman_db_password>'
    replace: "{{ foreman_db_password }}"

- name: Configure Nameservers of Foreman isntaller
  ansible.builtin.replace:
    path: /etc/foreman-installer/scenarios.d/foreman-answers.yaml
    regexp: '<foreman_dhcp_nameservers>'
    replace: "{{ foreman_dhcp_nameservers }}"

- name: Configure Admin username of Foreman isntaller
  ansible.builtin.replace:
    path: /etc/foreman-installer/scenarios.d/foreman-answers.yaml
    regexp: '<initial_admin_username>'
    replace: "{{ initial_admin_username }}"

- name: Configure Admin Password of Foreman isntaller
  ansible.builtin.replace:
    path: /etc/foreman-installer/scenarios.d/foreman-answers.yaml
    regexp: '<initial_admin_password>'
    replace: "{{ initial_admin_password }}"

- name: Configuring DHCP server of Foreman isntaller
  ansible.builtin.replace:
    path: /etc/foreman-installer/scenarios.d/foreman-answers.yaml
    regexp: '<dhcp_server>'
    replace: "{{ dhcp_server }}"

- name: Configuring isc-DHCP plugin of Foreman isntaller
  ansible.builtin.replace:
    path: /etc/foreman-installer/scenarios.d/foreman-answers.yaml
    regexp: '<dhcp_plugin>'
    replace: "{{ dhcp_plugin }}"

- name: Run Foreman installer
  retries: 2
  delay: 5
  become: yes
  script: install_foreman.py
  args:
    executable: python3
  register: foreman_installer_output

- name: Adding dhcpd.hosts config
  blockinfile :
    path: /etc/dhcp/dhcpd.hosts
    block: |
      host {{ item.hostname }} {
        hardware ethernet {{ item.macaddress }};
        fixed-address {{ item.ipaddress }};
      }
    state: present
    marker: "# {mark} ANSIBLE MANAGED BLOCK {{ item.hostname }}"
  with_items:
    - { hostname: test-vm2, macaddress: 08:00:27:6f:70:0c, ipaddress: 192.168.1.151 }
    - { hostname: test-vm, macaddress: 08:00:27:47:ef:9c, ipaddress: 192.168.1.150 }
    - { hostname: foreman-master, macaddress: e0:d5:5e:79:21:e0, ipaddress: 192.168.1.145 }